In [1]:
import numpy as np

## Datatypes and Attributes

In [2]:
# Numpy main datatype is nd-array
al = np.array([1,2,3])
al

array([1, 2, 3])

In [3]:
type(al)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3.3], [4,5,6.5]])

a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [12]:
a4 = np.array([[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                [10, 11, 12]],
                [[13, 14, 15],
                [16, 17, 18]]]);

In [13]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [14]:
a3.shape

(2, 3, 3)

In [15]:
a4.shape

(3, 2, 3)

In [16]:
al.shape

(3,)

In [17]:
a2.shape

(2, 3)

In [20]:
al.ndim, a2.ndim, a3.ndim, a3.shape, a4.ndim

(1, 2, 3, (2, 3, 3), 3)

In [21]:
a5 = np.array([[[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                [10, 11, 12]],
                [[13, 14, 15],
                [16, 17, 18]]]]);

In [22]:
a5.ndim

4

In [23]:
a5.shape

(1, 3, 2, 3)

In [25]:
al.dtype

dtype('int32')

In [27]:
a2.dtype

dtype('float64')

In [28]:
al.size, a2.size, a3.size, a4.size, a5.size

(3, 6, 18, 18, 18)

In [31]:
type(al), type(a2), type(a3), type(a4), type(a5)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Numpy Backbone

In [32]:
# Create a dataframe from a Numpy Array

import pandas as pd

In [33]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5