In [284]:
import numpy as np

## Datatypes and Attributes

In [285]:
# Numpy main datatype is nd-array
al = np.array([1,2,3])
al

array([1, 2, 3])

In [286]:
type(al)

numpy.ndarray

In [287]:
a2 = np.array([[1,2,3.3], [4,5,6.5]])

a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])

In [288]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [289]:
a4 = np.array([[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                [10, 11, 12]],
                [[13, 14, 15],
                [16, 17, 18]]]);

In [290]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [291]:
a3.shape

(2, 3, 3)

In [292]:
a4.shape

(3, 2, 3)

In [293]:
al.shape

(3,)

In [294]:
a2.shape

(2, 3)

In [295]:
al.ndim, a2.ndim, a3.ndim, a3.shape, a4.ndim

(1, 2, 3, (2, 3, 3), 3)

In [296]:
a5 = np.array([[[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                [10, 11, 12]],
                [[13, 14, 15],
                [16, 17, 18]]]]);

In [297]:
a5.ndim

4

In [298]:
a5.shape

(1, 3, 2, 3)

In [299]:
al.dtype

dtype('int32')

In [300]:
a2.dtype

dtype('float64')

In [301]:
al.size, a2.size, a3.size, a4.size, a5.size

(3, 6, 18, 18, 18)

In [302]:
type(al), type(a2), type(a3), type(a4), type(a5)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Numpy Backbone

In [303]:
# Create a dataframe from a Numpy Array

import pandas as pd

In [304]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Arrays

In [305]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [306]:
sample_array.dtype

dtype('int32')

In [307]:
ones = np.ones((2,3,4), dtype=int)
ones, ones.dtype, type(ones)

(array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]),
 dtype('int32'),
 numpy.ndarray)

In [308]:
zeros = np.zeros((2,3,4), dtype = int)
zeros, zeros.dtype

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 dtype('int32'))

In [309]:
range_array = np.arange(0, 100,0.5)
range_array

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5, 50. , 50.5, 51. , 51.5, 52. , 52.5, 53. , 53.5, 54. , 54.5,
       55. , 55.5, 56. , 56.5, 57. , 57.5, 58. , 58.5, 59. , 59.5, 60. ,
       60.5, 61. , 61.5, 62. , 62.5, 63. , 63.5, 64. , 64.5, 65. , 65.5,
       66. , 66.5, 67. , 67.5, 68. , 68.5, 69. , 69.5, 70. , 70.5, 71. ,
       71.5, 72. , 72.5, 73. , 73.5, 74. , 74.5, 75

In [310]:
random_array = np.random.randint(2,100, (4,9))
random_array

array([[36, 14,  6, 46, 57, 22, 45, 51, 20],
       [58, 23, 52, 24, 20, 71,  7,  7, 72],
       [97, 31, 18, 44, 48, 70, 79, 68, 14],
       [56, 90, 93, 57, 18,  7, 95, 75, 46]])

In [311]:
random_array.shape

(4, 9)

In [312]:
np.random.random((5,9))

array([[0.60924641, 0.14829474, 0.20769529, 0.72127594, 0.26758796,
        0.18489581, 0.81035698, 0.09103386, 0.12966964],
       [0.67959677, 0.44959741, 0.3896631 , 0.66184575, 0.01048353,
        0.26151906, 0.75223629, 0.93748825, 0.67568463],
       [0.49847177, 0.77532768, 0.56505187, 0.3038221 , 0.48092528,
        0.3150298 , 0.03802221, 0.56894916, 0.98576413],
       [0.37323235, 0.67976854, 0.12209437, 0.09265119, 0.63295346,
        0.28088024, 0.27140348, 0.89021819, 0.20350881],
       [0.29111026, 0.54722999, 0.71629064, 0.51835422, 0.7335823 ,
        0.05897287, 0.58623112, 0.58279402, 0.6280577 ]])

In [313]:
random_array_third = np.random.rand(5,4)
random_array_third

array([[0.71518211, 0.24324772, 0.72598572, 0.97045799],
       [0.37776588, 0.16968004, 0.3548634 , 0.60486355],
       [0.56297084, 0.62413032, 0.69169301, 0.43177954],
       [0.1799175 , 0.61705049, 0.42296652, 0.63253238],
       [0.90412283, 0.5991675 , 0.22163638, 0.20259745]])

In [314]:
np.random.seed(99999)


random_array_fourth = np.random.randint(10, size=(5,3))
random_array_fourth

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [315]:
np.random.seed(7)
random_array_fifth = np.random.random((5,3))
random_array_fifth

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [316]:
random_array_fifth = np.random.random((5,3))
random_array_fifth

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## Viewing Numpy Arrays and Matrices

In [317]:
 fourth_unique = np.unique(random_array)
 fourth_unique

array([ 6,  7, 14, 18, 20, 22, 23, 24, 31, 36, 44, 45, 46, 48, 51, 52, 56,
       57, 58, 68, 70, 71, 72, 75, 79, 90, 93, 95, 97])

In [318]:
al,a2,a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [319]:
al[0]

1

In [320]:
al[2]

3

In [321]:
a2[0]

array([1. , 2. , 3.3])

In [322]:
a2[0][1]

2.0

In [323]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [324]:
a3.shape

(2, 3, 3)

In [325]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [326]:
a3.shape

(2, 3, 3)

In [327]:
a2[1]

array([4. , 5. , 6.5])

In [328]:
a2[1][2]

6.5

In [329]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [330]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [331]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [332]:
a2[1,1]

5.0

In [333]:
a2[1][1]

5.0

In [334]:
aarray4 = np.random.randint(10, size = (2,3,4,5))

In [335]:
aarray4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [336]:
aarray4.shape, aarray4.ndim

((2, 3, 4, 5), 4)

In [337]:
aarray4[1][0][0], aarray4[1,0,0]

(array([6, 2, 6, 8, 2]), array([6, 2, 6, 8, 2]))

In [338]:
readingNumpyArrays = np.random.randint(10, size=(5,3,4))

In [339]:
readingNumpyArrays

array([[[1, 1, 5, 3],
        [2, 0, 4, 8],
        [7, 1, 4, 9]],

       [[3, 6, 7, 1],
        [0, 2, 7, 0],
        [0, 9, 8, 2]],

       [[0, 5, 5, 0],
        [9, 0, 8, 4],
        [5, 1, 4, 0]],

       [[7, 2, 0, 3],
        [9, 8, 3, 7],
        [1, 0, 1, 4]],

       [[6, 1, 0, 1],
        [0, 1, 8, 4],
        [1, 6, 8, 5]]])

In [340]:
readingNumpyArrays[1][1]

array([0, 2, 7, 0])

In [341]:
aarray4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [342]:
aarray4[0][1][2]

array([3, 0, 9, 9, 3])

In [343]:
aarray4[0].shape

(3, 4, 5)

In [344]:
aarray4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [345]:
aarray4[1][2][0]

array([0, 5, 7, 1, 8])

In [346]:
aarray4[1].shape

(3, 4, 5)

In [347]:
aarray4[:, :, :, :1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])

## 4. Manipulating & Comparing Numpy Arrays

### Arithmetic 

In [348]:
al

array([1, 2, 3])

In [349]:
ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [350]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [351]:
ones

array([1., 1., 1.])

In [352]:
al + ones, al, ones

(array([2., 3., 4.]), array([1, 2, 3]), array([1., 1., 1.]))

In [353]:
al - ones

array([0., 1., 2.])

In [354]:
al * ones

array([1., 2., 3.])

In [355]:
al / ones

array([1., 2., 3.])

In [356]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [357]:
a2 * al

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [358]:
a2 + ones

array([[2. , 3. , 4.3],
       [5. , 6. , 7.5]])

In [359]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [360]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [361]:
a3.ndim, a2.ndim

(3, 2)

In [362]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [91]:
 a3.shape

(2, 3, 3)

In [282]:
a2.shape

(2, 3)

In [283]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [121]:
np.reshape(a2, (2,3,1))

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [122]:
a3 * a2

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [123]:
a2

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [363]:
al / ones

array([1., 2., 3.])

In [365]:
a2 // al ## Floor division removes decimals (rounding the result down)

array([[1., 1., 1.],
       [4., 2., 2.]])

In [369]:
a2 / al

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [370]:
a2 ** al ## To the power e.g (2**2 = 4, 2**3 = 8)

array([[  1.   ,   4.   ,  35.937],
       [  4.   ,  25.   , 274.625]])

In [376]:
al, a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [378]:
al % 2

array([1, 0, 1], dtype=int32)

In [380]:
(a2 ** al) % 2

array([[1.   , 0.   , 1.937],
       [0.   , 1.   , 0.625]])

In [382]:
(a2 * al) % 2

array([[1. , 0. , 1.9],
       [0. , 0. , 1.5]])

In [383]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [385]:
np.exp(al)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [386]:
np.log(al)

array([0.        , 0.69314718, 1.09861229])

## Aggregation