In [1]:
import numpy as np

## Datatypes and Attributes

In [2]:
# Numpy main datatype is nd-array
al = np.array([1,2,3])
al

array([1, 2, 3])

In [3]:
type(al)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3.3], [4,5,6.5]])

a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a4 = np.array([[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                [10, 11, 12]],
                [[13, 14, 15],
                [16, 17, 18]]]);

In [7]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a4.shape

(3, 2, 3)

In [10]:
al.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
al.ndim, a2.ndim, a3.ndim, a3.shape, a4.ndim

(1, 2, 3, (2, 3, 3), 3)

In [13]:
a5 = np.array([[[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                [10, 11, 12]],
                [[13, 14, 15],
                [16, 17, 18]]]]);

In [14]:
a5.ndim

4

In [15]:
a5.shape

(1, 3, 2, 3)

In [16]:
al.dtype

dtype('int32')

In [17]:
a2.dtype

dtype('float64')

In [18]:
al.size, a2.size, a3.size, a4.size, a5.size

(3, 6, 18, 18, 18)

In [19]:
type(al), type(a2), type(a3), type(a4), type(a5)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Numpy Backbone

In [20]:
# Create a dataframe from a Numpy Array

import pandas as pd

In [21]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Arrays

In [22]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [23]:
sample_array.dtype

dtype('int32')

In [24]:
ones = np.ones((2,3,4), dtype=int)
ones, ones.dtype, type(ones)

(array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]),
 dtype('int32'),
 numpy.ndarray)

In [25]:
zeros = np.zeros((2,3,4), dtype = int)
zeros, zeros.dtype

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 dtype('int32'))

In [26]:
range_array = np.arange(0, 100,0.5)
range_array

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5, 50. , 50.5, 51. , 51.5, 52. , 52.5, 53. , 53.5, 54. , 54.5,
       55. , 55.5, 56. , 56.5, 57. , 57.5, 58. , 58.5, 59. , 59.5, 60. ,
       60.5, 61. , 61.5, 62. , 62.5, 63. , 63.5, 64. , 64.5, 65. , 65.5,
       66. , 66.5, 67. , 67.5, 68. , 68.5, 69. , 69.5, 70. , 70.5, 71. ,
       71.5, 72. , 72.5, 73. , 73.5, 74. , 74.5, 75

In [27]:
random_array = np.random.randint(2,100, (4,9))
random_array

array([[17, 48, 56,  8, 66, 35, 71,  8, 70],
       [ 4, 59,  2, 86, 37, 54, 46,  3,  7],
       [ 9, 13, 44, 52, 13, 34, 28, 99, 72],
       [13, 85, 15, 29, 90, 65, 77, 86, 93]])

In [28]:
random_array.shape

(4, 9)

In [29]:
np.random.random((5,9))

array([[0.52556351, 0.53112997, 0.39358478, 0.68967845, 0.60659012,
        0.05586394, 0.08354394, 0.92737118, 0.37070738],
       [0.34463381, 0.88424402, 0.03150077, 0.15056819, 0.81179798,
        0.98060263, 0.06036732, 0.69421989, 0.71229121],
       [0.02777602, 0.58922824, 0.70992028, 0.95685694, 0.39622049,
        0.86000645, 0.6175004 , 0.97250925, 0.28261093],
       [0.49389263, 0.7025138 , 0.26484281, 0.66900101, 0.09288145,
        0.77395697, 0.62995884, 0.57590484, 0.98186876],
       [0.40758046, 0.7704507 , 0.39513591, 0.04249179, 0.04781377,
        0.42854878, 0.95921939, 0.24849267, 0.33279327]])

In [30]:
random_array_third = np.random.rand(5,4)
random_array_third

array([[0.13408581, 0.59657956, 0.4979281 , 0.34588305],
       [0.33313539, 0.98788011, 0.20987187, 0.24449086],
       [0.83171494, 0.1572352 , 0.68385708, 0.67211083],
       [0.38593004, 0.88450017, 0.98697113, 0.99011408],
       [0.86074021, 0.26784744, 0.3465466 , 0.90394925]])

In [31]:
np.random.seed(99999)


random_array_fourth = np.random.randint(10, size=(5,3))
random_array_fourth

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [32]:
np.random.seed(7)
random_array_fifth = np.random.random((5,3))
random_array_fifth

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [33]:
random_array_fifth = np.random.random((5,3))
random_array_fifth

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## Viewing Numpy Arrays and Matrices

In [41]:
 fourth_unique = np.unique(random_array)
 fourth_unique

array([ 2,  3,  4,  7,  8,  9, 13, 15, 17, 28, 29, 34, 35, 37, 44, 46, 48,
       52, 54, 56, 59, 65, 66, 70, 71, 72, 77, 85, 86, 90, 93, 99])

In [43]:
al,a2,a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [44]:
al[0]

1

In [45]:
al[2]

3

In [46]:
a2[0]

array([1. , 2. , 3.3])

In [52]:
a2[0][1]

2.0

In [53]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
a3.shape

(2, 3, 3)

In [57]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [58]:
a3.shape

(2, 3, 3)

In [59]:
a2[1]

array([4. , 5. , 6.5])

In [61]:
a2[1][2]

6.5

In [62]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [63]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [64]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [66]:
a2[1,1]

5.0

In [67]:
a2[1][1]

5.0

In [69]:
aarray4 = np.random.randint(10, size = (2,3,4,5))

In [70]:
aarray4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [73]:
aarray4.shape, aarray4.ndim

((2, 3, 4, 5), 4)

In [77]:
aarray4[1][0][0], aarray4[1,0,0]

(array([6, 2, 6, 8, 2]), array([6, 2, 6, 8, 2]))

In [78]:
readingNumpyArrays = np.random.randint(10, size=(5,3,4))

In [79]:
readingNumpyArrays

array([[[1, 1, 5, 3],
        [2, 0, 4, 8],
        [7, 1, 4, 9]],

       [[3, 6, 7, 1],
        [0, 2, 7, 0],
        [0, 9, 8, 2]],

       [[0, 5, 5, 0],
        [9, 0, 8, 4],
        [5, 1, 4, 0]],

       [[7, 2, 0, 3],
        [9, 8, 3, 7],
        [1, 0, 1, 4]],

       [[6, 1, 0, 1],
        [0, 1, 8, 4],
        [1, 6, 8, 5]]])

In [84]:
readingNumpyArrays[1][1]

array([0, 2, 7, 0])

In [85]:
aarray4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [98]:
aarray4[0][1][2]

array([3, 0, 9, 9, 3])

In [89]:
aarray4[0].shape

(3, 4, 5)

In [99]:
aarray4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [103]:
aarray4[1][2][0]

array([0, 5, 7, 1, 8])

In [101]:
aarray4[1].shape

(3, 4, 5)