In [1]:
import numpy as np

## Datatypes and Attributes

In [2]:
# Numpy main datatype is nd-array
al = np.array([1,2,3])
al

array([1, 2, 3])

In [3]:
type(al)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3.3], [4,5,6.5]])

a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a4 = np.array([[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                [10, 11, 12]],
                [[13, 14, 15],
                [16, 17, 18]]]);

In [7]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a4.shape

(3, 2, 3)

In [10]:
al.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
al.ndim, a2.ndim, a3.ndim, a3.shape, a4.ndim

(1, 2, 3, (2, 3, 3), 3)

In [13]:
a5 = np.array([[[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                [10, 11, 12]],
                [[13, 14, 15],
                [16, 17, 18]]]]);

In [14]:
a5.ndim

4

In [15]:
a5.shape

(1, 3, 2, 3)

In [16]:
al.dtype

dtype('int32')

In [17]:
a2.dtype

dtype('float64')

In [18]:
al.size, a2.size, a3.size, a4.size, a5.size

(3, 6, 18, 18, 18)

In [19]:
type(al), type(a2), type(a3), type(a4), type(a5)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Numpy Backbone

In [20]:
# Create a dataframe from a Numpy Array

import pandas as pd

In [21]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Arrays

In [22]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [23]:
sample_array.dtype

dtype('int32')

In [24]:
ones = np.ones((2,3,4), dtype=int)
ones, ones.dtype, type(ones)

(array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]),
 dtype('int32'),
 numpy.ndarray)

In [25]:
zeros = np.zeros((2,3,4), dtype = int)
zeros, zeros.dtype

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 dtype('int32'))

In [26]:
range_array = np.arange(0, 100,0.5)
range_array

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5, 50. , 50.5, 51. , 51.5, 52. , 52.5, 53. , 53.5, 54. , 54.5,
       55. , 55.5, 56. , 56.5, 57. , 57.5, 58. , 58.5, 59. , 59.5, 60. ,
       60.5, 61. , 61.5, 62. , 62.5, 63. , 63.5, 64. , 64.5, 65. , 65.5,
       66. , 66.5, 67. , 67.5, 68. , 68.5, 69. , 69.5, 70. , 70.5, 71. ,
       71.5, 72. , 72.5, 73. , 73.5, 74. , 74.5, 75

In [27]:
random_array = np.random.randint(2,100, (4,9))
random_array

array([[29, 68, 34, 96, 58, 82, 93, 57, 90],
       [22, 36, 34, 24, 14, 14, 73, 66,  9],
       [15, 28, 82, 24, 78, 70, 69, 91, 68],
       [30, 76, 35, 98, 82, 10, 64, 32, 76]])

In [28]:
random_array.shape

(4, 9)

In [29]:
np.random.random((5,9))

array([[0.48968964, 0.0773052 , 0.7470088 , 0.41222268, 0.96380567,
        0.23656792, 0.58068934, 0.01096353, 0.81429998],
       [0.54306987, 0.50075078, 0.40736706, 0.93703238, 0.19515169,
        0.46500254, 0.74861577, 0.0115897 , 0.15493483],
       [0.10689423, 0.07853089, 0.67082966, 0.5769056 , 0.23816915,
        0.57201158, 0.86259089, 0.30666637, 0.15021354],
       [0.63835717, 0.9142111 , 0.81456211, 0.19738453, 0.93116914,
        0.59598162, 0.01257079, 0.12221013, 0.3553101 ],
       [0.39442703, 0.34837035, 0.32093733, 0.48831098, 0.04970332,
        0.95740019, 0.24198963, 0.39301802, 0.30910603]])

In [30]:
random_array_third = np.random.rand(5,4)
random_array_third

array([[0.33393255, 0.6958679 , 0.14052197, 0.75996437],
       [0.38863609, 0.52779227, 0.28567494, 0.98222577],
       [0.46421421, 0.41063689, 0.67271728, 0.58294284],
       [0.3793489 , 0.96777   , 0.24121886, 0.19216098],
       [0.99072386, 0.91722069, 0.99858983, 0.46735992]])

In [31]:
np.random.seed(99999)


random_array_fourth = np.random.randint(10, size=(5,3))
random_array_fourth

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [32]:
np.random.seed(7)
random_array_fifth = np.random.random((5,3))
random_array_fifth

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [33]:
random_array_fifth = np.random.random((5,3))
random_array_fifth

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## Viewing Numpy Arrays and Matrices

In [34]:
 fourth_unique = np.unique(random_array)
 fourth_unique

array([ 9, 10, 14, 15, 22, 24, 28, 29, 30, 32, 34, 35, 36, 57, 58, 64, 66,
       68, 69, 70, 73, 76, 78, 82, 90, 91, 93, 96, 98])

In [35]:
al,a2,a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [36]:
al[0]

1

In [37]:
al[2]

3

In [38]:
a2[0]

array([1. , 2. , 3.3])

In [39]:
a2[0][1]

2.0

In [40]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
a3.shape

(2, 3, 3)

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [43]:
a3.shape

(2, 3, 3)

In [44]:
a2[1]

array([4. , 5. , 6.5])

In [45]:
a2[1][2]

6.5

In [46]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [47]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [48]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [49]:
a2[1,1]

5.0

In [50]:
a2[1][1]

5.0

In [51]:
aarray4 = np.random.randint(10, size = (2,3,4,5))

In [52]:
aarray4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [53]:
aarray4.shape, aarray4.ndim

((2, 3, 4, 5), 4)

In [54]:
aarray4[1][0][0], aarray4[1,0,0]

(array([6, 2, 6, 8, 2]), array([6, 2, 6, 8, 2]))

In [55]:
readingNumpyArrays = np.random.randint(10, size=(5,3,4))

In [56]:
readingNumpyArrays

array([[[1, 1, 5, 3],
        [2, 0, 4, 8],
        [7, 1, 4, 9]],

       [[3, 6, 7, 1],
        [0, 2, 7, 0],
        [0, 9, 8, 2]],

       [[0, 5, 5, 0],
        [9, 0, 8, 4],
        [5, 1, 4, 0]],

       [[7, 2, 0, 3],
        [9, 8, 3, 7],
        [1, 0, 1, 4]],

       [[6, 1, 0, 1],
        [0, 1, 8, 4],
        [1, 6, 8, 5]]])

In [57]:
readingNumpyArrays[1][1]

array([0, 2, 7, 0])

In [58]:
aarray4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [59]:
aarray4[0][1][2]

array([3, 0, 9, 9, 3])

In [60]:
aarray4[0].shape

(3, 4, 5)

In [61]:
aarray4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [62]:
aarray4[1][2][0]

array([0, 5, 7, 1, 8])

In [63]:
aarray4[1].shape

(3, 4, 5)

In [64]:
aarray4[:, :, :, :1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])

## 4. Manipulating & Comparing Numpy Arrays

### Arithmetic 

In [65]:
al

array([1, 2, 3])

In [66]:
ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [67]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [68]:
ones

array([1., 1., 1.])

In [69]:
al + ones, al, ones

(array([2., 3., 4.]), array([1, 2, 3]), array([1., 1., 1.]))

In [70]:
al - ones

array([0., 1., 2.])

In [71]:
al * ones

array([1., 2., 3.])

In [72]:
al / ones

array([1., 2., 3.])

In [73]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [74]:
a2 * al

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [75]:
a2 + ones

array([[2. , 3. , 4.3],
       [5. , 6. , 7.5]])

In [76]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [77]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [78]:
a3.ndim, a2.ndim

(3, 2)

In [79]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [91]:
 a3.shape

(2, 3, 3)

In [282]:
a2.shape

(2, 3)

In [283]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [121]:
np.reshape(a2, (2,3,1))

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [122]:
a3 * a2

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [123]:
a2

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [363]:
al / ones

array([1., 2., 3.])

In [365]:
a2 // al ## Floor division removes decimals (rounding the result down)

array([[1., 1., 1.],
       [4., 2., 2.]])

In [369]:
a2 / al

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [370]:
a2 ** al ## To the power e.g (2**2 = 4, 2**3 = 8)

array([[  1.   ,   4.   ,  35.937],
       [  4.   ,  25.   , 274.625]])

In [376]:
al, a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [378]:
al % 2

array([1, 0, 1], dtype=int32)

In [380]:
(a2 ** al) % 2

array([[1.   , 0.   , 1.937],
       [0.   , 1.   , 0.625]])

In [382]:
(a2 * al) % 2

array([[1. , 0. , 1.9],
       [0. , 0. , 1.5]])

In [383]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [385]:
np.exp(al)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [386]:
np.log(al)

array([0.        , 0.69314718, 1.09861229])

## Aggregation

Agggregation  = performing the same operation on a number of things

In [80]:
listNumbers = [1,2,3]
type(listNumbers)

list

In [81]:
sum(listNumbers)

6

In [83]:
al

array([1, 2, 3])

In [87]:
np.sum(al)

6

## Use Python's methods on Python datatypes and use Numpy's methods on Numpy Arrays (`np.sum()`). 

In [96]:
# Creative a massive Numpy array
massive_array = np.random.random(100000);
massive_array.size

100000

In [100]:
%timeit sum(massive_array),  #Python's sum()
%timeit np.sum(massive_array) #Numpy's np.sum()

27.6 ms ± 660 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
81.7 µs ± 4.53 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [101]:
np.sum(listNumbers)

6

In [102]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [103]:
np.mean(a2)

3.6333333333333333

In [104]:
np.median(a2)

3.65

In [105]:
np.max(a2), np.min(a2)

(6.5, 1.0)

In [111]:
# Standard Deviation = a measure of how spread out a group of numbers is from the mean. 
np.std(a2)

1.8226964152656422

In [112]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = Lower range of numbers
np.var(a2)

3.3222222222222224

In [114]:
# Standard Deviation = SquareRoot of Variance... 
np.sqrt(np.var(a2))

1.8226964152656422

 ## Reshaping and Transposing

In [80]:
a2.shape

(2, 3)

In [81]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [82]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [83]:
a3.shape

(2, 3, 3)

In [89]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape, a2

(array([[[1. ],
         [2. ],
         [3.3]],
 
        [[4. ],
         [5. ],
         [6.5]]]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [88]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [91]:
# Understanding Transposing of Numpy Arrays
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [93]:
# Transpoe = Switches the axis of a Numpy Array.... 
a2.transpose()

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [94]:
a3, a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 (2, 3, 3))

In [96]:
a3.transpose().shape

(3, 3, 2)

In [103]:
a5.T.shape, a5.shape

((3, 2, 3, 1), (1, 3, 2, 3))

## Dot Product example (Nut Butter Sales)

In [80]:
np.random.seed(0)

#Number of jars sold
sales_amounts = np.random.randint(20, size = (5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [81]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts, index = ["Mon", "Tues", "Wed", "Thurs", "Fri"], columns= ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [91]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [89]:
# Create the prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [121]:
# reate Butter Prices Dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3), index= ["Price"], columns=["Almond Butter", "Peanut Butter", "Cashew Butter"]);
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [100]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [101]:
total_prices = np.dot(weekly_sales, butter_prices.T)

In [102]:
total_prices

array([[240],
       [138],
       [458],
       [232],
       [142]])

In [103]:
weekly_sales.dot(butter_prices.T)

Prices
Mon       240
Tues      138
Wed       458
Thurs     232
Fri       142

((3, 1), (5, 3))

In [113]:
# Create daily sales

butter_prices


Almond Butter  Peanut Butter  Cashew Butter
Prices             10              8             12

In [114]:
weekly_sales


Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [116]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [122]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [123]:
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [132]:
weekly_sales["Total of Sales in $"] = daily_sales.T

In [126]:
daily_sales.shape

(1, 5)

In [134]:
weekly_sales.shape, daily_sales.T.shape

((5, 4), (5, 1))

In [135]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total of Sales in $
Mon               12             15              0                  240
Tues               3              3              7                  138
Wed                9             19             18                  458
Thurs              4              6             12                  232
Fri                1              6              7                  142