In [60]:
import numpy as np

## Datatypes and Attributes

In [61]:
# Numpy main datatype is nd-array
al = np.array([1,2,3])
al

array([1, 2, 3])

In [62]:
type(al)

numpy.ndarray

In [63]:
a2 = np.array([[1,2,3.3], [4,5,6.5]])

a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])

In [64]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [65]:
a4 = np.array([[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                [10, 11, 12]],
                [[13, 14, 15],
                [16, 17, 18]]]);

In [66]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [67]:
a3.shape

(2, 3, 3)

In [68]:
a4.shape

(3, 2, 3)

In [69]:
al.shape

(3,)

In [70]:
a2.shape

(2, 3)

In [71]:
al.ndim, a2.ndim, a3.ndim, a3.shape, a4.ndim

(1, 2, 3, (2, 3, 3), 3)

In [72]:
a5 = np.array([[[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                [10, 11, 12]],
                [[13, 14, 15],
                [16, 17, 18]]]]);

In [73]:
a5.ndim

4

In [74]:
a5.shape

(1, 3, 2, 3)

In [75]:
al.dtype

dtype('int32')

In [76]:
a2.dtype

dtype('float64')

In [77]:
al.size, a2.size, a3.size, a4.size, a5.size

(3, 6, 18, 18, 18)

In [78]:
type(al), type(a2), type(a3), type(a4), type(a5)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Numpy Backbone

In [79]:
# Create a dataframe from a Numpy Array

import pandas as pd

In [80]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Arrays

In [81]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [82]:
sample_array.dtype

dtype('int32')

In [83]:
ones = np.ones((2,3,4), dtype=int)
ones, ones.dtype, type(ones)

(array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]),
 dtype('int32'),
 numpy.ndarray)

In [84]:
zeros = np.zeros((2,3,4), dtype = int)
zeros, zeros.dtype

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 dtype('int32'))

In [85]:
range_array = np.arange(0, 100,0.5)
range_array

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5, 50. , 50.5, 51. , 51.5, 52. , 52.5, 53. , 53.5, 54. , 54.5,
       55. , 55.5, 56. , 56.5, 57. , 57.5, 58. , 58.5, 59. , 59.5, 60. ,
       60.5, 61. , 61.5, 62. , 62.5, 63. , 63.5, 64. , 64.5, 65. , 65.5,
       66. , 66.5, 67. , 67.5, 68. , 68.5, 69. , 69.5, 70. , 70.5, 71. ,
       71.5, 72. , 72.5, 73. , 73.5, 74. , 74.5, 75

In [86]:
random_array = np.random.randint(2,100, (4,9))
random_array

array([[32, 89, 82, 12, 54, 58, 56, 13, 20],
       [40, 78, 83, 81, 77, 54, 40, 72, 66],
       [ 4, 27, 15,  8, 49, 39, 22, 30, 64],
       [37, 20, 74, 30, 22, 26, 71,  9, 99]])

In [87]:
random_array.shape

(4, 9)

In [88]:
np.random.random((5,9))

array([[0.70104894, 0.53663064, 0.74815763, 0.15796217, 0.1324834 ,
        0.28073514, 0.60185095, 0.7186027 , 0.2520158 ],
       [0.09648879, 0.03527946, 0.40689825, 0.3050009 , 0.14535391,
        0.82884852, 0.1097517 , 0.74739518, 0.32852455],
       [0.0831779 , 0.82003221, 0.26163323, 0.91765152, 0.32032986,
        0.29600608, 0.69019911, 0.4385758 , 0.72933324],
       [0.0140967 , 0.53619781, 0.29709521, 0.94093311, 0.28732922,
        0.67413451, 0.54892921, 0.78233554, 0.44079386],
       [0.49270213, 0.57524812, 0.03418818, 0.7441069 , 0.88905964,
        0.85045161, 0.2312245 , 0.7763463 , 0.08607835]])

In [89]:
random_array_third = np.random.rand(5,4)
random_array_third

array([[0.80390891, 0.77082892, 0.11186789, 0.87054696],
       [0.24854623, 0.54379049, 0.30061943, 0.61369332],
       [0.21227775, 0.04944765, 0.35790596, 0.50207735],
       [0.86038928, 0.25718078, 0.08272123, 0.42528195],
       [0.37542414, 0.6479548 , 0.66127789, 0.83987188]])

In [106]:
np.random.seed(99999)


random_array_fourth = np.random.randint(10, size=(5,3))
random_array_fourth

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [117]:
np.random.seed(7)
random_array_fifth = np.random.random((5,3))
random_array_fifth

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [120]:
random_array_fifth = np.random.random((5,3))
random_array_fifth

array([[0.71932412, 0.41299183, 0.90642327],
       [0.18045162, 0.74111887, 0.42237404],
       [0.42645357, 0.63437987, 0.5229062 ],
       [0.41488598, 0.00142688, 0.09226235],
       [0.70939439, 0.5243456 , 0.69616046]])