# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1])
print(" ----------- ")
print("One Dimensional Array")
print(a1)
print(a1.ndim)

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2], [3,4], [5,6]])
print(" ----------- ")
print("Two-Dimensional Array")
print(a2, a2.ndim, a2.shape)

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(" ----------- ")
print("Three Dimensional Array")
a3, a3.ndim, a3.shape

 ----------- 
One Dimensional Array
[1]
1
 ----------- 
Two-Dimensional Array
[[1 2]
 [3 4]
 [5 6]] 2 (3, 2)
 ----------- 
Three Dimensional Array


(array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]),
 3,
 (1, 3, 3))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim, a1.dtype, a1.shape, type(a1), a1.size

(1, dtype('int32'), (1,), numpy.ndarray, 1)

In [5]:
# Attributes of 2-dimensional array
a2.ndim, a2.dtype, a2.shape, type(a2), a2.size

(2, dtype('int32'), (3, 2), numpy.ndarray, 6)

In [6]:
# Attributes of 3-dimensional array
a3.ndim, a3.dtype, a3.shape, type(a3), a3.size

(3, dtype('int32'), (1, 3, 3), numpy.ndarray, 9)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
twoFrame = pd.DataFrame(a2)
twoFrame

0  1
0  1  2
1  3  4
2  5  6

In [8]:
# Create an array of shape (10, 2) with only ones
onlyOnes = np.ones([10,2])
onlyOnes, onlyOnes.ndim, onlyOnes.shape

(array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 2,
 (10, 2))

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
onlyZeros = np.zeros([7,2,3])
onlyZeros, onlyZeros.ndim, onlyZeros.shape

(array([[[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]]]),
 3,
 (7, 2, 3))

In [10]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array, range_array.shape, range_array.size, range_array.ndim

(array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
        51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]),
 (34,),
 34,
 1)

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0, 10, size = [7,2])
random_array, random_array.size, random_array.shape, random_array.ndim

(array([[2, 3],
        [5, 4],
        [4, 8],
        [8, 6],
        [7, 3],
        [9, 3],
        [1, 2]]),
 14,
 (7, 2),
 2)

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
float_random_array = np.random.randint(0,1,size=[3,5]).astype("float")
float_random_array, float_random_array.shape, float_random_array.dtype

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 (3, 5),
 dtype('float64'))

In [13]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_one_zero = np.random.randint(0, 1, size = (4,6))
random_array_one_zero, random_array_one_zero.shape, random_array_one_zero.dtype

(array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]),
 (4, 6),
 dtype('int32'))

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

Not sure... why it's happening

In [14]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_variable = np.random.randint(1,10, size=(3,7))
print(random_array_variable)


# Find the unique numbers in the array you just created
np.unique(random_array_variable)

[[7 4 8 5 7 3 7]
 [8 5 4 8 8 3 6]
 [5 2 8 6 2 5 1]]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
# Find the 0'th index of the latest array you created
random_array_variable[0:1]

array([[7, 4, 8, 5, 7, 3, 7]])

In [55]:
# Get the first 2 rows of latest array you created

random_array_variable[0:2]

array([[7, 4, 8, 5, 7, 3, 7],
       [8, 5, 4, 8, 8, 3, 6]])

In [105]:
# Get the first 2 values of the first 2 rows of the latest array
slicedarray_one = random_array_variable[0:2][0:1]
slicedarray_one.resize(7)

#First 2 Values of the First Row
print(slicedarray_one[0:2])

slicedarray_two = random_array_variable[0:2][1:2]
slicedarray_two.resize(7)

#First 2 Values of the Second Row
print(slicedarray_two[0:2])



[7 4]
[8 5]


In [106]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

random_array_one_ten = np.random.randint(1,10, size=(3,5))
one_array_threefive = np.ones([3,5])

random_array_one_ten, one_array_threefive


(array([[6, 9, 1, 3, 7],
        [4, 9, 3, 5, 3],
        [7, 5, 9, 7, 2]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [107]:
# Add the two arrays together
random_array_one_tenrandom_array_one_ten + one_array_threefive


array([[ 7., 10.,  2.,  4.,  8.],
       [ 5., 10.,  4.,  6.,  4.],
       [ 8.,  6., 10.,  8.,  3.]])

In [110]:
# Create another array of ones of shape (5, 3)

one_array_five_three = np.ones([5,3])
one_array_five_three


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [111]:
# Try add the array of ones and the other most recent array together
one_array_five_three + one_array_threefive

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

I remember that is happening because the arrays can't be broadcasted together... Not sure why the broadcasting can't happen. 

How would you fix it?
By resizing the shape of one of the arrays to have the shapes match

In [112]:
# Create another array of ones of shape (3, 5)
one_array_three_five_second = np.ones([3,5])
one_array_three_five_second

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [115]:
# Subtract the new array of ones from the other most recent array
random_array_one_ten - one_array_three_five_second

array([[5., 8., 0., 2., 6.],
       [3., 8., 2., 4., 2.],
       [6., 4., 8., 6., 1.]])

In [116]:
# Multiply the ones array with the latest array
random_array_one_ten * one_array_three_five_second

array([[6., 9., 1., 3., 7.],
       [4., 9., 3., 5., 3.],
       [7., 5., 9., 7., 2.]])

In [119]:
# Take the latest array to the power of 2 using '**'
random_array_one_ten ** one_array_three_five_second

array([[6., 9., 1., 3., 7.],
       [4., 9., 3., 5., 3.],
       [7., 5., 9., 7., 2.]])

In [120]:
# Do the same thing with np.square()
np.square(random_array_one_ten)


array([[36, 81,  1,  9, 49],
       [16, 81,  9, 25,  9],
       [49, 25, 81, 49,  4]], dtype=int32)

In [121]:
# Find the mean of the latest array using np.mean()
np.mean(random_array_one_ten)


5.333333333333333

In [122]:
# Find the maximum of the latest array using np.max()
np.max(random_array_one_ten)


9

In [123]:
# Find the minimum of the latest array using np.min()
np.min(random_array_one_ten)

1

In [124]:
# Find the standard deviation of the latest array
np.std(random_array_one_ten)

2.547329756605707

In [125]:
# Find the variance of the latest array
np.var(random_array_one_ten)

6.48888888888889

In [130]:
# Reshape the latest array to (3, 5, 1)
new_reshaped_array = random_array_one_ten.reshape([3,5,1])
new_reshaped_array.shape, new_reshaped_array

((3, 5, 1),
 array([[[6],
         [9],
         [1],
         [3],
         [7]],
 
        [[4],
         [9],
         [3],
         [5],
         [3]],
 
        [[7],
         [5],
         [9],
         [7],
         [2]]]))

In [133]:
# Transpose the latest array
random_array_one_ten.transpose()

array([[6, 4, 7],
       [9, 9, 5],
       [1, 3, 9],
       [3, 5, 7],
       [7, 3, 2]])

What does the transpose do?

Flips the axis around... 

In [138]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

random_array_for_dot = np.random.randint(1,10, size=(3,3))
second_random_array_for_dot= np.random.randint(1,10, size=(3,2))

random_array_for_dot, second_random_array_for_dot


(array([[8, 9, 9],
        [1, 9, 7],
        [9, 8, 1]]),
 array([[8, 8],
        [3, 1],
        [8, 3]]))

In [140]:
# Perform a dot product on the two newest arrays you created
print(np.dot(random_array_for_dot, second_random_array_for_dot))
random_array_for_dot.shape, second_random_array_for_dot.shape


[[163 100]
 [ 91  38]
 [104  83]]


((3, 3), (3, 2))

In [142]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

random_array_for_transposed = np.random.randint(1,10, size=(4,3))
second_random_array_for_transposed= np.random.randint(1,10, size=(4,3))

random_array_for_transposed, second_random_array_for_transposed


(array([[7, 7, 9],
        [3, 7, 1],
        [4, 4, 5],
        [7, 7, 4]]),
 array([[7, 3, 6],
        [2, 9, 5],
        [6, 4, 7],
        [9, 7, 1]]))

In [143]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_for_transposed, second_random_array_for_transposed)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

By transposing one of the two arrays

In [38]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [39]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [40]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [41]:
# Compare the two arrays with '>='


In [42]:
# Find which elements of the first array are greater than 7


In [43]:
# Which parts of each array are equal? (try using '==')


In [44]:
# Sort one of the arrays you just created in ascending order


In [45]:
# Sort the indexes of one of the arrays you just created


In [46]:
# Find the index with the maximum value in one of the arrays you've created


In [47]:
# Find the index with the minimum value in one of the arrays you've created


In [48]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [49]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [50]:
# Create an array of normally distributed random numbers


In [51]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.